"""Optional, retrieval-assisted English continuations for the MICA demo.

This module is separate from the reference decoder. It retrieves complete
sentences from a bounded, TRAIN-only English index, matches the prompt's last
two or more words, and uses the exported integer MICA model to rerank the first
eight bytes of the continuation. A suggestion is an excerpt of a training
sentence, not text freely generated by MICA; train-line provenance makes
that visible to callers. URL/title/license are unavailable in this internal
prototype's text-only corpus.

The index builder reads the entire train.txt stream but retains at most
``max_sentences`` sentences, chosen by stable SHA-256 priority. It removes
sentences that occur verbatim in sibling val.txt or test.txt files. Build
provenance and source file hashes are saved beside the index.
"""

from __future__ import annotations

import argparse
from collections import Counter
from dataclasses import dataclass
import hashlib
import heapq
import json
import math
import os
from pathlib import Path
import re
from typing import Iterable

from .suggest import ByteScorer, _log_probs
from .topic_consistency import TopicConsistency


WORD = re.compile(r"[A-Za-z]+(?:['\u2019][A-Za-z]+)*")
SENTENCE_BOUNDARY = re.compile(r"(?<=[.!?])\s+(?=[\"'\u201c\u2018(]*[A-Za-z])")
TERMINAL = re.compile(r"[.!?][\"'\u201d\u2019)]*$")
SPACES = re.compile(r"\s+")
CLAUSE_BREAK = re.compile(r",|;|:\s|\s(?:and|but|while|because)\s", re.I)
PURPOSE_BREAK = re.compile(r"\b(?:time|today|tomorrow)(?=\s+to\b)", re.I)
QUESTION_START = re.compile(
    r"^\s*(?:who|what|where|when|why|how|which|can|could|would|will|"
    r"do|does|did|is|are|was|were|have|has|should|may)\b", re.I)
QUESTION_END = re.compile(r"\?([\"'\u201d\u2019)]*)$")
STOPWORDS = frozenset("""
    a an the and or but of on in to for from with at by about as that this
    these those is are was were be been being do does did have has had will
    would can could should may might must i you he she it we they me him her
    them my your his its our their who what when where why how if then so
    not no yes please very just all any some one two into over under again
    there here than also more most before after get got getting take took
    taking want wants wanted moved move moving hard
""".split())


def _topic_key(word: str) -> str:
    """Fold a few productive English endings for source/prompt topic overlap."""
    word = word.casefold()
    if word.endswith("ing") and len(word) > 5:
        root = word[:-3]
        return root[:-1] if len(root) > 3 and root[-1] == root[-2] else root
    if word.endswith("ies") and len(word) > 5:
        return word[:-3] + "y"
    if word.endswith("s") and len(word) > 4 and not word.endswith("ss"):
        return word[:-1]
    return word


def _sha256_file(path: Path) -> str:
    result = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            result.update(block)
    return result.hexdigest()


def _normal(text: str) -> str:
    return SPACES.sub(" ", text).strip().casefold()


def _sentences(record: str) -> Iterable[str]:
    for part in SENTENCE_BOUNDARY.split(record.strip()):
        sentence = SPACES.sub(" ", part).strip()
        if sentence:
            yield sentence


def _quality(sentence: str) -> bool:
    """Conservative source filter; avoids incomplete or markup-like excerpts."""
    words = list(WORD.finditer(sentence))
    if not 7 <= len(words) <= 40 or len(sentence.encode("utf-8")) > 256:
        return False
    if not TERMINAL.search(sentence) or not sentence[0].isupper():
        return False
    if sentence[0] in "([{<" or "http" in sentence.lower() or "www." in sentence:
        return False
    if any(mark in sentence for mark in ("{", "}", "|", "\\", "=", "`")):
        return False
    letters = sum(ch.isalpha() for ch in sentence)
    if letters / max(len(sentence), 1) < 0.60:
        return False
    if sum(ch.isdigit() for ch in sentence) / len(sentence) > 0.10:
        return False
    return True


def build_index(train_file: str | Path, out_dir: str | Path, *,
                max_sentences: int = 50_000) -> dict:
    """Build a deterministic bounded index, excluding sibling val/test text.

    Requiring the split names and both held-out files makes accidentally
    indexing evaluation records considerably harder. The original corpus
    builder also deduplicates exact records globally and splits by document.
    """
    train = Path(train_file).resolve()
    out = Path(out_dir).resolve()
    if train.name != "train.txt":
        raise ValueError("retrieval source must be a train.txt split")
    if not train.is_file():
        raise FileNotFoundError(train)
    if max_sentences < 1:
        raise ValueError("max_sentences must be positive")
    heldout = [train.with_name("val.txt"), train.with_name("test.txt")]
    for path in heldout:
        if not path.is_file():
            raise FileNotFoundError(f"held-out exclusion file is required: {path}")
    if out.exists() and any(out.iterdir()):
        raise FileExistsError(f"index directory is not empty: {out}")

    excluded: set[str] = set()
    for path in heldout:
        with path.open("r", encoding="utf-8") as stream:
            for record in stream:
                excluded.update(_normal(sentence) for sentence in _sentences(record))

    # Largest priority at heap root; replacement retains the global minimum
    # priorities regardless of source order. Entries are unique by normalized
    # sentence. A selected duplicate cannot improve the current heap.
    heap: list[tuple[int, int, str, int, int, str]] = []
    selected: set[str] = set()
    counts = {"records_scanned": 0, "sentences_scanned": 0,
              "quality_rejected": 0, "heldout_rejected": 0,
              "selected_duplicate_rejected": 0}
    with train.open("r", encoding="utf-8") as stream:
        for line_no, record in enumerate(stream, 1):
            counts["records_scanned"] += 1
            for ordinal, sentence in enumerate(_sentences(record)):
                counts["sentences_scanned"] += 1
                if not _quality(sentence):
                    counts["quality_rejected"] += 1
                    continue
                normal = _normal(sentence)
                if normal in excluded:
                    counts["heldout_rejected"] += 1
                    continue
                key = hashlib.sha256(normal.encode("utf-8")).hexdigest()
                if key in selected:
                    counts["selected_duplicate_rejected"] += 1
                    continue
                priority = int(key[:16], 16)
                # Negative priority and line make heap[0] the worst entry.
                item = (-priority, -line_no, key, line_no, ordinal, sentence)
                if len(heap) < max_sentences:
                    heapq.heappush(heap, item)
                    selected.add(key)
                elif item > heap[0]:
                    old = heapq.heapreplace(heap, item)
                    selected.remove(old[2])
                    selected.add(key)

    out.mkdir(parents=True, exist_ok=True)
    index_file = out / "sentences.jsonl"
    with index_file.open("w", encoding="utf-8", newline="\n") as stream:
        for _, _, key, line_no, ordinal, sentence in sorted(heap, key=lambda e: (e[2], e[3])):
            stream.write(json.dumps({"text": sentence, "train_line": line_no,
                                     "sentence_ordinal": ordinal,
                                     "normalized_sha256": key,
                                     "source_url": None, "source_title": None,
                                     "source_license": None}, ensure_ascii=False) + "\n")
    corpus_manifest = train.with_name("manifest.json")
    manifest = {
        "format": "mica-retrieval-sentences-v1",
        "source_split": "train",
        "publication_ready": False,
        "attribution_status": "source URL, title and license unavailable in train.txt",
        "source_train_file": str(train),
        "source_train_sha256": _sha256_file(train),
        "excluded_files": [{"path": str(p), "sha256": _sha256_file(p)} for p in heldout],
        "excluded_unique_sentences": len(excluded),
        "corpus_manifest_sha256": (_sha256_file(corpus_manifest)
                                   if corpus_manifest.is_file() else None),
        "sampling": "minimum SHA-256 priority over every quality-passing train sentence",
        "max_sentences": max_sentences,
        "selected_sentences": len(heap),
        "index_sha256": _sha256_file(index_file),
        "counts": counts,
    }
    (out / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n",
                                       encoding="utf-8")
    return manifest


@dataclass(frozen=True)
class Sentence:
    text: str
    train_line: int
    sentence_ordinal: int
    normalized_sha256: str
    source_url: str | None = None
    source_title: str | None = None
    source_license: str | None = None


class SentenceIndex:
    def __init__(self, sentences: list[Sentence], manifest: dict):
        self.sentences = sentences
        self.manifest = manifest
        self.words = [list(WORD.finditer(s.text)) for s in sentences]
        # One posting per token position; queries verify the preceding words.
        self.postings: dict[str, list[tuple[int, int]]] = {}
        for index, matches in enumerate(self.words):
            for position, match in enumerate(matches):
                self.postings.setdefault(match.group().casefold(), []).append((index, position))
        self.topic = TopicConsistency(self)

    @classmethod
    def load(cls, out_dir: str | Path) -> SentenceIndex:
        out = Path(out_dir)
        manifest = json.loads((out / "manifest.json").read_text(encoding="utf-8"))
        if manifest.get("format") != "mica-retrieval-sentences-v1" or manifest.get("source_split") != "train":
            raise ValueError("not a train-only MICA retrieval index")
        path = out / "sentences.jsonl"
        if _sha256_file(path) != manifest["index_sha256"]:
            raise ValueError("retrieval index does not match its manifest")
        with path.open("r", encoding="utf-8") as stream:
            sentences = [Sentence(**json.loads(line)) for line in stream]
        if len(sentences) != manifest["selected_sentences"]:
            raise ValueError("retrieval index sentence count differs from manifest")
        return cls(sentences, manifest)


@dataclass(frozen=True)
class RetrievalSuggestion:
    continuation: str
    full_text: str
    source_sentence: str
    source_train_line: int
    source_sentence_ordinal: int
    source_corpus: str | None
    source_url: str | None
    source_title: str | None
    source_license: str | None
    matched_words: int
    collocation_support: int
    topic_overlap: float
    topic_signal: float
    topic_anchor: str | None
    topic_candidate_word: str | None
    topic_joint_sentences: int
    constructed_punctuation: bool
    model_mean_logp: float
    model_scored_bytes: int
    rank_score: float


@dataclass(frozen=True)
class RetrievalResult:
    suggestions: tuple[RetrievalSuggestion, ...]
    abstained: bool
    reason: str
    method: str = "train-corpus retrieval, integer MICA rerank"


@dataclass(frozen=True)
class _Match:
    sentence_index: int
    continuation: str
    matched_words: int
    topic_overlap: float
    partial_word: bool


def _matches(index: SentenceIndex, prompt: str, *, min_match_words: int,
             max_match_words: int) -> list[_Match]:
    prompt_words = list(WORD.finditer(prompt))
    if len(prompt_words) < min_match_words:
        return []
    tail = prompt[prompt_words[-1].end():]
    at_word_end = not tail
    prompt_tokens = [word.group().casefold() for word in prompt_words]
    # The final word may be complete or a partially typed word. Both paths
    # are valid; a partial path needs at least one exact word before it.
    variants: list[tuple[bool, list[tuple[int, int]]]] = []
    variants.append((False, index.postings.get(prompt_tokens[-1], [])))
    if at_word_end and len(prompt_tokens[-1]) >= 2:
        pref = prompt_tokens[-1]
        partial_positions = [position for word, positions in index.postings.items()
                             if word.startswith(pref) and word != pref
                             for position in positions]
        variants.append((True, partial_positions))

    found: dict[tuple[int, str], _Match] = {}
    for partial, positions in variants:
        for sentence_idx, position in positions:
            sentence = index.sentences[sentence_idx].text
            sentence_words = index.words[sentence_idx]
            preceding = len(prompt_tokens) - 1
            available = position
            max_check = min(preceding, available, max_match_words - 1)
            matched = 0
            for offset in range(1, max_check + 1):
                if (sentence_words[position - offset].group().casefold()
                        != prompt_tokens[-1 - offset]):
                    break
                matched += 1
            matched_words = matched + 1
            if matched_words < min_match_words:
                continue
            if partial:
                original_word = sentence_words[position].group()
                if original_word.casefold() == prompt_tokens[-1]:
                    continue
                # Token matching is casefolded; ASCII only, so the character
                # offset is the same in the source sentence.
                start = sentence_words[position].start() + len(prompt_words[-1].group())
            else:
                start = sentence_words[position].end()
                if tail:
                    if not sentence[start:].startswith(tail):
                        continue
                    start += len(tail)
            continuation = sentence[start:]
            if prompt and prompt[-1].isspace():
                continuation = continuation.lstrip()
            if not continuation or not WORD.search(continuation):
                continue
            # Words before the matched phrase determine whether the source
            # sentence is about the same topic as the caller's prompt. Common
            # function words carry almost no topical evidence.
            context = set(prompt_tokens[:-matched_words]) - STOPWORDS
            source_prefix = {_topic_key(word.group())
                             for word in sentence_words[:position - matched]}
            overlap = sum(min(6.0, math.log((len(index.sentences) + 1) /
                                            (len(index.postings.get(word, ())) + 1)))
                          for word in context
                          if _topic_key(word) in source_prefix)
            key = (sentence_idx, continuation)
            candidate = _Match(sentence_idx, continuation, matched_words, overlap,
                               partial)
            if key not in found or candidate.matched_words > found[key].matched_words:
                found[key] = candidate
    return list(found.values())


def _shorten(text: str, max_words: int) -> str:
    words = list(WORD.finditer(text))
    if len(words) <= max_words:
        return text
    count = max_words
    while (count < min(len(words), max_words + 4) and
           words[count - 1].group().casefold() in STOPWORDS):
        count += 1
    end = words[count - 1].end()
    # Keep terminal punctuation immediately after the final word.
    punctuation = re.match(r"[.!?,;:]+", text[end:])
    if punctuation:
        end += len(punctuation.group())
    return text[:end].rstrip()


def _sentence_clause(text: str) -> tuple[str, bool]:
    """End a source clause before it switches to a second event or topic."""
    break_points = [match.start() for match in CLAUSE_BREAK.finditer(text)]
    # A purpose infinitive following a complete time expression often refers
    # to the source sentence's subject. Ending there keeps the prompt's own
    # subject coherent ("arrive on time to meet..." -> "arrive on time.").
    break_points.extend(match.end() for match in PURPOSE_BREAK.finditer(text))
    for point in sorted(break_points):
        before = text[:point].rstrip()
        if WORD.search(before):
            return before.rstrip(" ,;:" ) + ".", True
    return text, False


def _align_terminal(prompt: str, continuation: str,
                    constructed: bool) -> tuple[str, bool]:
    """Avoid copying a question mark onto a declarative/imperative prompt."""
    if not QUESTION_START.match(prompt):
        match = QUESTION_END.search(continuation)
        if match:
            return continuation[:match.start()] + "." + match.group(1), True
    return continuation, constructed


def _mean_logp(scorer: ByteScorer, initial: object, continuation: str,
               max_scored_bytes: int) -> tuple[float, int]:
    raw = continuation.encode("utf-8")[:max_scored_bytes]
    state = initial
    total = 0.0
    for byte in raw:
        total += float(_log_probs(scorer.scores(state))[byte])
        state = scorer.advance(state, byte)
    return total / len(raw), len(raw)


def suggest_retrieval(scorer: ByteScorer, index: SentenceIndex, prompt: str, *,
                      mode: str = "sentence", max_words: int = 8,
                      min_match_words: int = 2, max_match_words: int = 8,
                      shortlist: int = 48, top_k: int = 3,
                      model_scored_bytes: int = 8) -> RetrievalResult:
    """Retrieve coherent source continuations, then rerank with MICA.

    Lexical match length dominates: MICA's observed useful horizon is short,
    so a high byte likelihood cannot override a clearly better phrase match.
    The returned model score is a local heuristic, not a confidence measure.
    """
    if mode not in {"short", "sentence"}:
        raise ValueError("mode must be 'short' or 'sentence'")
    if min_match_words < 2 or max_match_words < min_match_words:
        raise ValueError("require at least a 2-word trailing match")
    if min(max_words, shortlist, top_k, model_scored_bytes) < 1:
        raise ValueError("limits must be positive")
    if not prompt or not prompt.strip():
        return RetrievalResult((), True, "prompt_too_short")
    matches = _matches(index, prompt, min_match_words=min_match_words,
                       max_match_words=max_match_words)
    if not matches:
        return RetrievalResult((), True, "no_two_word_train_match")
    # Treat a final prompt word as complete whenever exact whole-word source
    # matches exist. Partial-word completion is a fallback for typed prefixes.
    if any(not match.partial_word for match in matches):
        matches = [match for match in matches if not match.partial_word]
    # Preserve the best lexical matches before the bounded model pass.
    matches.sort(key=lambda m: (-m.matched_words, -m.topic_overlap,
                                index.sentences[m.sentence_index].normalized_sha256,
                                m.continuation))
    best_match = matches[0].matched_words
    matches = [m for m in matches if m.matched_words == best_match]
    next_words = [WORD.search(m.continuation).group().casefold() for m in matches]
    support = Counter(next_words)
    matches = matches[:shortlist]
    initial = scorer.start(prompt.encode("utf-8"))
    ranked = []
    for match in matches:
        source = index.sentences[match.sentence_index]
        next_word = WORD.search(match.continuation).group().casefold()
        count = support[next_word]
        if mode == "sentence":
            continuation, constructed = _sentence_clause(match.continuation)
            if len(list(WORD.finditer(continuation))) > 16:
                continue
        else:
            clause, constructed = _sentence_clause(match.continuation)
            continuation = _shorten(clause, max_words)
            if continuation != clause:
                constructed = False
        continuation, constructed = _align_terminal(prompt, continuation,
                                                     constructed)
        if not continuation:
            continue
        model_mean, nbytes = _mean_logp(scorer, initial, continuation,
                                        model_scored_bytes)
        prefix_content = {w.group().casefold() for w in list(WORD.finditer(prompt))
                          [:-match.matched_words]} - STOPWORDS
        tail_content = {w.group().casefold() for w in list(WORD.finditer(prompt))
                        [-match.matched_words:]} - STOPWORDS
        suffix_words = len(list(WORD.finditer(continuation)))
        if prefix_content and not tail_content and match.topic_overlap == 0:
            continue
        # With only a generic two-word tail and a rich earlier context,
        # require source-topic evidence or a well-supported short collocation.
        if (match.matched_words == 2 and len(prefix_content) >= 2 and
                match.topic_overlap == 0 and
                not (count >= 2 and suffix_words <= 5) and
                not (model_mean > -0.65 and suffix_words <= 5)):
            continue
        if (match.matched_words == 3 and len(prefix_content) >= 3 and
                match.topic_overlap == 0 and suffix_words > 8):
            continue
        semantic = index.topic.score(prompt, continuation,
                                     match.matched_words)
        score = (model_mean + 0.60 * math.log1p(count) +
                 0.25 * min(match.topic_overlap, 8.0) -
                 0.025 * suffix_words +
                 0.20 * min(semantic.value, 1.5))
        ranked.append(RetrievalSuggestion(
            continuation=continuation, full_text=prompt + continuation,
            source_sentence=source.text, source_train_line=source.train_line,
            source_sentence_ordinal=source.sentence_ordinal,
            source_corpus=index.manifest.get("source_train_file"),
            source_url=source.source_url, source_title=source.source_title,
            source_license=source.source_license,
            matched_words=match.matched_words,
            collocation_support=count, topic_overlap=match.topic_overlap,
            topic_signal=semantic.value, topic_anchor=semantic.anchor,
            topic_candidate_word=semantic.candidate_word,
            topic_joint_sentences=semantic.joint_sentences,
            constructed_punctuation=constructed,
            model_mean_logp=model_mean,
            model_scored_bytes=nbytes, rank_score=score))
    ranked.sort(key=lambda s: (-s.rank_score, -s.matched_words,
                               s.source_train_line, s.continuation))
    unique: dict[str, RetrievalSuggestion] = {}
    for item in ranked:
        unique.setdefault(item.continuation, item)
    result = tuple(list(unique.values())[:top_k])
    return RetrievalResult(result, not bool(result), "ok" if result else "no_usable_continuation")


def suggest_retrieval_fallback(scorer: ByteScorer,
                               indexes: Iterable[SentenceIndex], prompt: str,
                               **kwargs) -> RetrievalResult:
    """Use a second train-only corpus only when the primary one abstains.

    This keeps a broad, noisier source from displacing a coherent result from
    the primary everyday corpus. Each result retains its own corpus path and
    train-line provenance.
    """
    attempted = 0
    last: RetrievalResult | None = None
    for index in indexes:
        attempted += 1
        last = suggest_retrieval(scorer, index, prompt, **kwargs)
        if not last.abstained:
            return last
    if not attempted:
        raise ValueError("at least one retrieval index is required")
    return last


def _cli() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    build = commands.add_parser("build", help="build a bounded index from train.txt")
    build.add_argument("--train", type=Path, required=True)
    build.add_argument("--out", type=Path, required=True)
    build.add_argument("--max-sentences", type=int, default=50_000)
    query = commands.add_parser("suggest", help="query an exported MICA model")
    query.add_argument("--run", type=Path, required=True)
    query.add_argument("--index", type=Path, required=True)
    query.add_argument("--fallback-index", type=Path,
                       help="query this train-only index only if primary abstains")
    query.add_argument("--prompt", required=True)
    query.add_argument("--mode", choices=("short", "sentence"), default="sentence")
    query.add_argument("--max-words", type=int, default=8)
    query.add_argument("--top-k", type=int, default=3)
    query.add_argument("--shortlist", type=int, default=48)
    args = parser.parse_args()
    if args.command == "build":
        print(json.dumps(build_index(args.train, args.out,
                                     max_sentences=args.max_sentences), indent=2))
        return
    info = json.loads((args.run / "run_info.json").read_text(encoding="utf-8"))
    os.environ.update({key: str(value) for key, value in info["env"].items()})
    # spec binds geometry at import time, so import the model after run_info.
    from . import serialize
    from .suggest import MicaScorer
    model = serialize.load(args.run / "best.mica")
    indexes = [SentenceIndex.load(args.index)]
    if args.fallback_index:
        indexes.append(SentenceIndex.load(args.fallback_index))
    result = suggest_retrieval_fallback(MicaScorer(model), indexes, args.prompt,
                                        mode=args.mode, max_words=args.max_words,
                                        top_k=args.top_k, shortlist=args.shortlist)
    print(json.dumps({"abstained": result.abstained, "reason": result.reason,
                      "method": result.method,
                      "suggestions": [s.__dict__ for s in result.suggestions]},
                     ensure_ascii=False, indent=2))


if __name__ == "__main__":
    _cli()
