#!/usr/bin/env python3
"""Samples, generation speed and peak memory of exported models (.mica).

Inference implementation: mica_r1/engine.py, the single-session integer
reference engine (numpy, one Python process, one stream). For every model:

  * samples: BOS, then the prompt's bytes, then N generated bytes. Each byte
    is drawn from softmax(score / 1024 / T) over the 256 byte values (EOS and
    BOS are excluded, so every sample has exactly N bytes), with a numpy
    PCG64 generator seeded per (prompt, seed) -- the same seeds for every
    model. Output bytes are shown as UTF-8 with invalid sequences replaced.
    Sampling at a temperature is not the R1 reference decoder (which is
    greedy); it is the evaluation setting asked for.
  * speed: wall time of the generation loop only (score all symbols, sample,
    ingest), over all samples, as generated bytes per second; the prompt
    prefill is timed separately.
  * memory: this process's peak resident set (RSS / Windows peak working
    set), measured in a fresh process per model: Python + numpy + the model.
    The interpreter-only baseline (same imports, no model) is measured the
    same way, so the model's own share can be read off.

    python r1/checks/sample_gen.py --run best=r1/runs/sweep/p32_5bit_self1 \
        --run previous=r1/runs/sweep/p16_tiefix --out r1/runs/checks/samples.json
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import utf8_stdout, run_geometry, worker_env, peak_rss_bytes, cpu_name, beat

PROMPTS = ["The weather ", "I want to ", "Today we ", "The cat "]


def worker(a) -> int:
    import numpy as np
    rss_start = peak_rss_bytes()
    from mica_r1 import spec, serialize, engine
    rss_imports = peak_rss_bytes()
    if a.baseline_only:
        Path(a.out).write_text(json.dumps({"rss_after_imports": rss_imports,
                                           "rss_start": rss_start}))
        return 0
    assert engine.ROUTING_MODE == "pairdiff", engine.ROUTING_MODE
    m = serialize.load(a.mica)
    seeds = [int(s) for s in a.seeds.split(",")]
    samples, gen_time, gen_bytes, pre_time, pre_bytes = [], 0.0, 0, 0.0, 0
    for prompt in PROMPTS:
        for seed in seeds:
            beat(f"sampling {prompt!r} {seed}")
            rng = np.random.Generator(np.random.PCG64(seed))
            t0 = time.perf_counter()
            s = engine.new_session(m)                  # zero field, ingest BOS
            for b in prompt.encode("utf-8"):
                engine.ingest(m, s, b)
            t1 = time.perf_counter()
            out = bytearray()
            for _ in range(a.bytes):
                sc = engine.probe_scores(m, s)[:256].astype(np.float64)
                x = sc / spec.LOGIT_DIVISOR / a.temperature
                p = np.exp(x - x.max())
                p /= p.sum()
                b = int(rng.choice(256, p=p))
                out.append(b)
                engine.ingest(m, s, b)
            t2 = time.perf_counter()
            pre_time += t1 - t0
            pre_bytes += len(prompt.encode("utf-8")) + 1
            gen_time += t2 - t1
            gen_bytes += a.bytes
            samples.append({"prompt": prompt, "seed": seed,
                            "text": out.decode("utf-8", errors="replace"),
                            "bytes_hex": out.hex()})
    res = {"mica": a.mica, "file_bytes": Path(a.mica).stat().st_size,
           "samples": samples, "temperature": a.temperature,
           "generated_bytes": gen_bytes,
           "generation_bytes_per_s": gen_bytes / gen_time,
           "prefill_bytes_per_s": pre_bytes / pre_time,
           "rss_start": rss_start, "rss_after_imports": rss_imports,
           "peak_rss": peak_rss_bytes(), "ticks": spec.MAX_TICKS,
           "cells": spec.N_CELLS, "channels": spec.N_CHANNELS,
           "implementation": "mica_r1/engine.py (numpy reference engine, "
                             "single session, single process)",
           "numpy": np.__version__, "python": sys.version.split()[0],
           "cpu": cpu_name()}
    Path(a.out).write_text(json.dumps(res, indent=1))
    return 0


def main() -> int:
    utf8_stdout()
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", action="append", default=[])
    ap.add_argument("--seeds", default="0,1")
    ap.add_argument("--bytes", type=int, default=200)
    ap.add_argument("--temperature", type=float, default=0.7)
    ap.add_argument("--out")
    ap.add_argument("--worker", action="store_true")
    ap.add_argument("--baseline-only", action="store_true")
    ap.add_argument("--mica")
    a = ap.parse_args()
    if a.worker:
        return worker(a)
    out_path = Path(a.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    results = json.loads(out_path.read_text()) if out_path.exists() else {}
    # interpreter + numpy + mica_r1 imports, no model: the memory floor
    tmp = out_path.with_name(out_path.stem + ".baseline.part.json")
    first_geom = run_geometry(Path(a.run[0].split("=", 1)[1]))
    subprocess.run([sys.executable, __file__, "--worker", "--baseline-only",
                    "--out", str(tmp)], env=worker_env(first_geom), check=True)
    results["_interpreter_baseline"] = json.loads(tmp.read_text())
    tmp.unlink()
    for item in a.run:
        name, run_dir = item.split("=", 1)
        run_dir = Path(run_dir)
        tmp = out_path.with_name(out_path.stem + f".{name}.part.json")
        cmd = [sys.executable, __file__, "--worker", "--mica",
               str(run_dir / "best.mica"), "--seeds", a.seeds,
               "--bytes", str(a.bytes), "--temperature", str(a.temperature),
               "--out", str(tmp)]
        p = subprocess.run(cmd, env=worker_env(run_geometry(run_dir)),
                           capture_output=True, text=True, encoding="utf-8")
        if p.returncode:
            print(f"[samples] {name}: FAILED\n{p.stderr[-3000:]}", flush=True)
            continue
        r = json.loads(tmp.read_text(encoding="utf-8"))
        tmp.unlink()
        r["run_dir"] = str(run_dir)
        results[name] = r
        out_path.write_text(json.dumps(results, indent=1))
        mb = lambda x: f"{x / 2**20:.1f} MiB" if x else "n/a"
        print(f"[samples] {name}: {r['generation_bytes_per_s']:.1f} bytes/s "
              f"generating, {r['prefill_bytes_per_s']:.1f} bytes/s prefill, "
              f"peak RSS {mb(r['peak_rss'])} (interpreter + imports "
              f"{mb(r['rss_after_imports'])}), file {r['file_bytes']:,} B, "
              f"{r['cpu']}", flush=True)
        for s in r["samples"]:
            print(f"[samples] {name} seed {s['seed']}: {s['prompt']!r} + "
                  f"{s['text']!r}", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
